config/routes.rb
Essentialreadinglist::Application.routes.draw do
  resources :comments
  resources :books do
    collection do
      match 'search' => 'books#index', :via => [:get, :post], :as => :search
    end
  end
  resources :ratings, only: :update
  match '/search', to: 'books#search', via: 'get'
  match '/search_gwerl', to: 'books#search_gwerl', via: 'get'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root "static_pages#intro"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def intro
  end

  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page], :per_page => 5)
      @books = current_user.books.paginate(page: params[:page], :per_page => 10)
      @new_books = my_latest_books_added(current_user)
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About')%>

	<h1>About us</h1>

	<p>The Great War's Essential Booklist v2.0.1</p>
</br>

	<p>Created and maintained by LiteHouse Development</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%>

	<h1>Contact us</h1>
	

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>

	<h1>Help</h1>

<p> The help page is under construction </p>

<p> Use the contact page to contact us when you require help</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home')%>

<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>	
			<section>
				 <%= render 'shared/micropost_form' %>
			</section>	
			<section>
				<p>My recent contributions...</p>
				<%= render 'shared/new_books' %>
			</section>
		
		</aside>
		<div class="span8">
			<section>
				<h3>Micropost Feed</h3>
				<%= render 'shared/feed' %>
			</section>
			<section>
				<% if @user.books.any? %>
				<h3>My Books</h3>
				<ol class="microposts">
					<%= render @books %>
				</ol>
				<%= will_paginate @books %>
				<% end %>
			</section>
		</div>	
	</div>
<% else %>		
<div class="center hero-unit">

	<h1>The Great War's Essential Reading List</h1>

	<h2>The most complete reference of books about the Great War.
		</h2>
		
		<div class="row">
			<div class= "span6 offset3">
				
				<%= form_for(:session, url: sessions_path) do |f| %>

					<%= f.text_field :email, :placeholder => "email" %></br>

		  			<%= f.password_field :password , :placeholder => "password" %></br>

					<%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
				<% end %>

				<p>New user? <%= link_to "Sign up now!", signup_path %></p>
			</div>
		</div>
		<%= link_to image_tag("gwerl.png", alt: "Gwerl") %>
</div>
	
<iframe src="http://www.facebook.com/plugins/like.php?href=http://essentialreadinglist.heroku.com/"
        scrolling="no" frameborder="0"
        style="border:none; width:450px; height:70px"></iframe>
<% end %>

app/views/static_pages/intro.html.erb
<% provide(:title, 'Intro')%>

	
	<header id="header">
		<h1 id="cie-name">The Great War's Essential Reading List</h1>
	</header>

	<nav id="next-btn">
    	<%= link_to "Skip intro", home_path  %>
	</nav>
	
	<section id="stats">
		<h3><%= book_stats%> Books and <%= user_stats%> Users</h3>
	</section>


	<video id="video_background" preload="auto" autoplay="true" loop="loop">
	 	<source src="http://www.lihoa.com/MediaLib/The_Battle_of_Passchendaele_World_War_I.mp4" >
	</video>