config/routes.rb
Essentialreadinglist::Application.routes.draw do
  resources :comments
  resources :books do
    collection do
      match 'search' => 'books#index', :via => [:get, :post], :as => :search
    end
  end
  resources :ratings, only: :update
  match '/search', to: 'books#search', via: 'get'
  match '/search_gwerl', to: 'books#search_gwerl', via: 'get'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root "static_pages#intro"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :identifier, uniqueness: { case_sensitive: false }
 
  BOOK_IDENTIFIER_TYPES = ["isbn", "ASIN", "Olid"]
  BOOK_SEARCH_CRITERIA = ["titel", "author", "isbn", "ASIN", "Olid"]
  
  def average_rating
    if self.ratings.size > 0
      self.ratings.average(:score).round(0)
    else
      return 0
    end
  end
  
  
  
  #Ruby
  def is_valid?(isbn)
    (isbn.length == 10) && (isbn.split('').inject([10,0]){|a, c| i,s = a; [s+i*c.to_i,i-1]}.first%11==0)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :signed_in_user, only: [ :edit, :update, :destroy, :update ]
  
  
  
  def new
    @book = Book.new
  end

  def index
    @q = Book.search(params[:q])
    @books = @q.result(distinct: true).paginate(page: params[:page], :per_page => 10)
    @new_books = latest_books_added
  end

  def show
    @book = Book.find(params[:id])
    current_book=(@book)
    @amazon_url= amazon_url(@book.identifier) unless (@book.identifier_type == "Olid")
    @comment = @book.comments.build
    @comments = @book.comments.paginate(page: params[:page], :per_page => 10)
    if signed_in?
      @rating = Rating.where(book_id: @book.id, user_id: current_user.id).first
      @rating = Rating.create(book_id: @book.id, user_id: current_user.id) unless @rating 
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "A new book is added to the GWERL"
      redirect_to @book
    else
      render :new
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted."
    redirect_to books_url
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] =  "Book updated"
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  def search
    begin
      search_criterion = params[:search_criterion]
      search_value = params[:q]
      book_details = nil
      case search_criterion 
        when "ASIN"
          book_params = lookup_book_via_ASIN(search_value) 
          @book = Book.new(book_params) unless book_params.nil?
          render 'new'
        when "Olid"
          book_params = lookup_book_via_olid(search_value)
          @book = Book.new(book_params) unless book_params.nil?
          render 'new'
        else
          book_details =  lookup_book_via(search_criterion, search_value)
          if book_details.nil?
            flash[:error] = "Nothing found"
            redirect_to new_book_path
          else
            author, publisher, amazon_url, isbn = "unknown "
            author = book_details.authors.first["name"] unless book_details.authors.nil?
            publisher = book_details.publishers[0]["name"] unless book_details.publishers.nil?
            isbn = book_details.identifiers["isbn_10"].to_s[2..11] unless book_details.identifiers.nil?
            if !isbn.nil?
              search_value = isbn
              search_criterion = "Isbn"
              img_url = lookup_image_on_Amazon(isbn)
            end
            if img_url.nil?
              data = Openlibrary::Data
              book = data.find_by_isbn(isbn)
              img_url = book.cover["large"]
            end
            amazon_url = amazon_url(isbn) unless isbn.nil?
            book_params = {:title => book_details.title, :authors => author, :publisher => publisher, :identifier => search_value, :identifier_type => search_criterion, :img_url => img_url } 
            @book = Book.new(book_params)
            render 'new'
          end
        end
      rescue
        logger.error "Search returned an unexpected error" 
        flash[:error] = "An error occurred whilst searching external libraries"
        redirect_to new_book_path
      end
  end
  
  def search_gwerl
   @books = Book.paginate(page: params[:page], :per_page => 10)
  end
  
  def lookup_book_via(search_criterion, search_value)
    case search_criterion
    when "isbn"
      book_details = lookup_book_via_isbn(search_value)
    when "title"
      book_details = lookup_book_via_title(search_value)
    when "author"
      book_details = lookup_book_via_author(search_value)
    else
      flash[:error]= "Invalid serach criterion: #{search_criterion}"
      book_details = nil
    end
  end
  
  def lookup_book_via_isbn(isbn)
    begin
      data = Openlibrary::Data
      book_details = data.find_by_isbn(isbn)
    rescue  => e
      logger.error "Openlibrary API DATA Isbn error"
    end
  end
  
  def lookup_book_via_olid(olid)
    
    begin
      isbn = nil
      
      identifier = olid
      identifier_type = "Olid"
      
      client = Openlibrary::Client.new
      
      book = client.book(olid)
      isbn = book.isbn_10[0] unless book.isbn_10.nil?
      title = book.title
      author = book.by_statement
      publisher = book.publishers[0] unless book.publishers.nil?
      img_url = book.thumbnail_url
      
      if img_url.nil?
        data = Openlibrary::Data
        book = data.find_by_olid(olid)
        img_url = book.cover["large"]
      end
      
      if !isbn.nil?
        identifier = isbn
        identifier_type = "Isbn"
        img_url = lookup_image_on_Amazon(isbn)
      end
      book_params = {:title => title, :authors => author, :publisher => publisher, :identifier => identifier, :identifier_type => identifier_type, :img_url => img_url } 
    rescue => e
      logger.error "Openlibrary API CLIENT Olid error"
    end
    return book_params
  end
  
  
  def lookup_book_via_ASIN(asin)
    begin
      
      res = Amazon::Ecs.item_lookup(asin, { :response_group => "Medium"})
      book = res.items.first
      
      item_attributes = book.get_element("ItemAttributes")
      img_url = book.get("MediumImage/URL").to_s
      
      title = item_attributes.get("Title")
      author = item_attributes.get("Author")
      publisher = item_attributes.get("Manufacturer")
          
      book_params = {:title => title, :authors => author, :publisher => publisher, :identifier => asin, :identifier_type => "ASIN", :img_url => img_url } 

    rescue => e
      logger.error "Amazon search failed"
      flash[:error] = "Amazon search failed"
    end
    return book_params
  end
  
  def lookup_image_on_Amazon(asin)
    begin
      
      res = Amazon::Ecs.item_lookup(asin, { :response_group => "Medium"})
      book = res.items.first
      img_url = book.get("MediumImage/URL").to_s
      
    rescue => e
      logger.error "Amazon search failed"
      flash[:error] = "Amazon search failed"
    end
    return img_url
  end
  
  def lookup_book_via_title(title)
    begin
      client = Openlibrary::Client.new
      books = client.search(title)
    rescue Exception => e
      logger.error "Openlibrary API CLIENT title error"
    end
    
    if !books[0].nil? && !books[0].isbn.nil?
      isbn = nil
      isbn = books[0].isbn[0]
      book_details = lookup_book_via_isbn(isbn) unless isbn.nil?
    end
    
  end
  
  def lookup_book_via_author(author)
    begin
      client = Openlibrary::Client.new
      books = client.search({ author: "#{author}"} )
    rescue Exception => e
      logger.error "Openlibrary API CLIENT author error"
    end
    isbn = books[0].isbn[0]
    book_details = lookup_book_via_isbn(isbn) unless isbn.nil?
  end
  
  
  private
  
  def book_params
    params.require(:book).permit( :title, :authors, :publisher, :identifier, :identifier_type, :creator_id, :img_url  )
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<li>
	<%= image_tag book.img_url, size: "30x30" %>
	<%= link_to book.title, book %>, by
	<%= book.authors %>, published by  
	<%= book.publisher %>
	
</li>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_field :title, :placeholder => "title" %></br>

  <%= f.text_field :authors, :placeholder => "authors" %></br>

  <%= f.text_field :identifier, :placeholder => "isbn" %></br>

  <%= f.text_field :identifier_type, :placeholder => "isbn10/13/ASIN/Olid/Other" %></br>

  <%= f.text_field :publisher, :placeholder => "publisher" %></br>

  <%= f.text_field :img_url, :placeholder => "image url" %></br>

  <div><%= f.hidden_field :creator_id %></div>

	<%= f.submit %>
	<%= link_to "Search a book ...", "#", class: "btn btn-large" %>
<% end %>

	

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<%= provide(:title, 'Edit Book') %>

<h1>Editing <%= @book.title %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.text_field :title, :placeholder => "title" %></br>

	  <%= f.text_field :authors, :placeholder => "authors" %></br>

	  <%= f.text_field :identifier, :placeholder => "identifier" %></br>

	  <%= f.select :identifier_type, Book::BOOK_IDENTIFIER_TYPES, :prompt => 'Select type' %></br>

	  <%= f.text_field :publisher, :placeholder => "publisher" %></br>

	  <%= f.text_field :img_url, :placeholder => "image url" %></br>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<%= link_to "Cancel", book_path, class: "btn btn-large" %>
	<% end %>
  </div>
</div>

app/views/books/index.html.erb
<% provide(:title, "All the Books") %>

<div class="row">
	<aside class="span3">
		
		<section>
			<h3>Search the GWERL</h3>
		</section>

		<section>
			<%= search_form_for @q do |f| %>
				<%= f.text_field :title_cont, :placeholder => "title"  %>
				<%= f.text_field :authors_cont, :placeholder => "author"  %>
				<%= f.text_field :publisher_cont, :placeholder => "publisher"  %>
				<%= f.text_field :identifier_cont, :placeholder => "isbn, asin, olid"  %>
				 <%= f.submit class: "btn" %>
				<% end %>
		</section>
		<% if signed_in? %>
			<section>
				<%= link_to "Add new book", new_book_path, class: "btn btn-large btn-primary" %>
			</section>	
		<% end %>
		<section>
			<h3>Recently added...</h3>
			<%= render 'shared/new_books' %>
		</section>
				
	</aside>
	<div class="span8">
		<h3>The Great War's Essential Reading List</h3>
		<%= will_paginate @books%>

		<ul class="books">
				<%= render @books %>
		</ul>

		<%= will_paginate @books %>
	</div>	
</div>

app/views/books/new.html.erb
<%= provide(:title, 'Add Book') %>

<h1>Add a Book to the GWERL</h1>

<div class="row">
	
	<aside class="span3">
		<section>
			<h3>Search a book on the Internet</h3>
		</section>
			
		<section>
			<%= form_tag("/search", method: "get") do %>
			  Searck a book based on:
			  <%= select_tag(:search_criterion, options_for_select([['title', "title"], ['author', "author"], ['Isbn', "Isbn"], ['ASIN - Amazon', "ASIN"], ['Olid - Openlibrary', "Olid"] ])) %>
			  <%= label_tag(:q, "Search for:") %>
			  <%= text_field_tag(:q) %>
			  <%= submit_tag "Search", class: "btn btn-large" %>
			<% end %>
		</section>
		
		<section>
		</section>
	</aside>
	
	<div class="span6">
		
		<%= form_for(@book) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>

		  <%= f.text_field :title, :placeholder => "title" %></br>

		  <%= f.text_field :authors, :placeholder => "authors" %></br>

		  <%= f.text_field :identifier, :placeholder => "isbn" %></br>

		  <%= f.select :identifier_type, Book::BOOK_IDENTIFIER_TYPES, :prompt => 'Select type' %></br>

		  <%= f.text_field :publisher, :placeholder => "publisher" %></br>

		  <%= f.text_field :img_url, :placeholder => "image url" %></br>

		  <div><%= f.hidden_field :creator_id, :value => current_user.id %></div>

			<%= f.submit "Save book", class: "btn btn-large btn-primary" %>
			<%= link_to "Cancel", new_book_path, class: "btn btn-large" %>

		<% end %>
	</div>	
</div>

app/views/books/search.html.erb
<h1>Books#search</h1>
<p>Find me in app/views/books/search.html.erb</p>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= @book.title %> 
			</h1>			
		</section>
		<section>
			<div id="star"></div>
		</section>
		<section>
			<% creator = User.find(@book.creator_id) %>
			<p><%= image_tag @book.img_url, size: "120x120" %></p>
			<p>Authors: <%= @book.authors %></p>
			<p>Published by: <%= @book.publisher %></p>
			<P>Identifier: <%= @book.identifier %></p>
			<% if signed_in? %>
				<P>Book added by: <%= link_to(creator.name,creator) %> </p>
				<p>Rate this book  <div id="user_star"></div></p>
			<% end %>	
		</section>
		<% if signed_in? %>
			<section>
				<%= link_to "Edit", edit_book_path, class: "btn btn-large btn-primary" %>
				<%= link_to "Delete", book_path(@book), :method => "delete" , data: { confirm: "Sure ?"}, class: "btn btn-large" %>
			</section>
		<% end %>	
		<section>
			<% unless @amazon_url == "unknown" %>
				Buy this book: 
				<p><%= link_to "On Amazon", @amazon_url %></p>
			<% end %>
		</section>
		<section>
			<!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style ">
				<a class="addthis_button_preferred_1"></a>
				<a class="addthis_button_preferred_2"></a>
				<a class="addthis_button_preferred_3"></a>
				<a class="addthis_button_preferred_4"></a>
				<a class="addthis_button_compact"></a>
				<a class="addthis_counter addthis_bubble_style"></a>
			</div>
			<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-52442ce57a2dd99d"></script>
			<!-- AddThis Button END -->
		</section>
	</aside>
	
	<div class="span8">
		<h1>Book Reviews</h1>
		<% if signed_in? %>
	 		<section>
			 	<%= render 'shared/comment_form' %>
			</section>
		<% end %>	
		<section>
			<% if !(@book.comments.count == 0) %>
			<h3>Book reviews: (<%= @book.comments.count %>)</h3>
			<ol class="microposts">
				<%= render @comments %>
			</ol>
			<%= will_paginate @comments %>
			<% else %>
				<% if signed_in? %>
					<P>Be the first to write a review for this book...</p>
				<% else %>
					<P>Sign up to be the first to write a review for this book...</p>
				<% end %>
			<% end %>
		</section>
	</div>		
	<div class="span8">
		<section>
		 	section to display additional info about the books, dynamic content, book reviews, etc...
		</section>
	</div>
</div>

<script>

  $('#star').raty({
    readOnly: true,
    score: <%= @book.average_rating %>,
    path: "/assets"
  });


<% if signed_in? %>
  $('#user_star').raty({
    score: <%= @rating.score %>,
    path: "/assets",
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= @rating.id %>,
        type: 'PATCH',
        data: { score: score }
      });
    }
  });
<% end %>
</script>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>