config/routes.rb
Essentialreadinglist::Application.routes.draw do
  resources :comments
  resources :books do
    collection do
      match 'search' => 'books#index', :via => [:get, :post], :as => :search
    end
  end
  resources :ratings, only: :update
  match '/search', to: 'books#search', via: 'get'
  match '/search_gwerl', to: 'books#search_gwerl', via: 'get'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root "static_pages#intro"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/views/layouts/_footer.html.erb
	<footer class="footer">
		<small>
			The Gwerl &copy 2013 LiteHouse Development
		</small>
		<nav><ul>
			<li><%= link_to(image_tag("Facebook-icon.png", size: "30x30"), "https://www.facebook.com/greatwar.fourteeneighteen") %> </li>
			<li><%= link_to(image_tag("tumblr-logo.png", size: "30x30"), "http://greatwar1418.tumblr.com") %> </li>
			<li><%= link_to(image_tag("twitter-icon.png", size: "30x30"), "https://twitter.com/greatwar1418") %> </li>
			<li><%= link_to "About", about_path %> </li>
			</ul>
		</nav>	
	</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Gwerl", root_path, id: "logo" %> 
			
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", home_path  %></li>
					<li><%= link_to "Books", books_path  %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path  %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" >
							<%= "#{current_user.name}" %> <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	
	<%= render 'layouts/header' unless yield(:title) == 'Intro' %>
	<div class="container">	
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>			
		<%= yield %>
		<%= render 'layouts/footer' unless yield(:title) == 'Intro' %>
	</div>
		
</body>
</html>